### ISSUE TITLE
Error in React Native: console.groupCollapsed, nice to have: Better error message

### ISSUE THREAD

**Issue by vikeri** [day8/re-frame-tracer#4]
I got the following error when working with `re-frame` and `re-natal` and enabled tracing:

```
[TypeError: console.groupCollapsed is not a function. (In 'console.groupCollapsed("%c%s",[cljs.core.str("color:"),cljs.core.str(self__.color),cljs.core.str(";")].join(''),title)', 'console.groupCollapsed' is undefined)] line: 112, column: 23
```

I got it because I had by accident disabled Chrome Debugging in the simulator. Enable it and it worked again. 

**Solution**: Enable Debug JS Remotely

So its not really an issue but if one could print a more helpful error message somehow I'd be willing to contribute with a PR if someone points me in the right direction.

**Comment by danielcompton** [comment]
The logic is in https://github.com/Day8/re-frame-tracer/blob/master/src/re_frame_tracer/core.cljs. You will need to check if console.groupcollapsed is supported before using it. I'm not really sure what the right error message here is though as re-frame is used in lots of places. 

Perhaps a good first step is a PR for the docs?

**Comment by vikeri** [comment]
Yes, it is a stupid mistake (if you want debugging you probably think of enabling it on the emulator) so if anyone else runs into this at least there will be search results on Google now. An actual code fix might be overkill. 
Added it to the Debug section of the Wiki as well: https://github.com/Day8/re-frame/wiki/Debugging#react-native
